name: Deploy to Server

on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Create inventory.ini file
      run: |
        echo "${{ secrets.INVENTORY_INI }}" > .github/workflows/inventory.ini

    - name: Create privkey file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > .github/workflows/privkey
        chmod 600 .github/workflows/privkey


    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "false"
      run: |
        ansible-playbook -i .github/workflows/inventory.ini .github/workflows/deploy_message.yml --extra-vars "ansible_become_pass=${{ secrets.SERVER_SUDO_PASS }}" --private-key .github/workflows/privkey
