name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  dockerloginbuildpush:
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: tradelocker
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/checkout@v2
      - name: create image from repository
        run: docker build -t ghcr.io/tradelocker/tradelocker:latest .
      - name: push image to GitHub Container Registry
        run: docker push ghcr.io/tradelocker/tradelocker:latest
