name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${CR_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/tradelocker:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/tradelocker:latest
