name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tradelocker:latest

      - name: Debug Docker username
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: Tag the Docker image
        run: docker tag tradelocker:latest ${{ secrets.DOCKER_USERNAME }}/tradelocker:latest

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tradelocker:latest
