name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set repository owner to lowercase
        id: prep
        run: echo "repository_owner_lower=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ env.repository_owner_lower }}/tradelocker:latest

      - name: Push the Docker image
        run: docker push ghcr.io/${{ env.repository_owner_lower }}/tradelocker:latest
